name: Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - uses: action/setup-node@v2
    with:
      node-version: 16.x
      cache: 'npm'
    - run: npm i
    - run: npm run build